---
kind: ConfigMap
apiVersion: v1

metadata:
  name: redis-db-sample
data:
  application.properties: |
    #set your ip for the services here!
    spring.redis.host=pjmtest.hmbfpj.0001.euc1.cache.amazonaws.com
    spring.datasource.url=jdbc:mysql://pjmtest.cozdzhn9o9c4.eu-central-1.rds.amazonaws.com:3306/debe?useSSL=false
    spring.datasource.username=debe
    spring.datasource.password=debe
---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: redis-db-sample
  labels:
    app: redis-db-sample

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-db-sample
  template:
    metadata:
      labels:
        app: redis-db-sample
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: redis-db-sample
      containers:
        - name: redis-db-sample
          image: sothawo/redis-db-sample:0.0.1
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /config
          ports:
          - name: redis-db-sample
            containerPort: 8080
          resources:
            requests:
              cpu: 0.1
              memory: 500M
            limits:
              cpu: 1
              memory: 700M
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/
---
kind: Service
apiVersion: v1

metadata:
  name: redis-db-sample

spec:
  selector:
    app: redis-db-sample

  type: LoadBalancer

  ports:
    - port: 8080
      targetPort: 8080
