---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: redis
  labels:
    app: redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
          - name: redis
            containerPort: 6379
          resources:
            requests:
              cpu: 0.1
              memory: 500M
            limits:
              cpu: 1
              memory: 700M
---
kind: Service
apiVersion: v1

metadata:
  name: redis

spec:
  selector:
    app: redis

  type: ClusterIP

  ports:
    - port: 6379
      targetPort: 6379
